# Generated by Django 2.0.2 on 2018-07-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='Szkoła pełna nazwa')),
                ('street', models.CharField(max_length=100, verbose_name='Ulica')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('voivodeship', models.CharField(max_length=100, verbose_name='Województwo')),
                ('authority', models.CharField(max_length=100, verbose_name='Miasto')),
            ],
            options={
                'verbose_name': 'Szkoła',
                'verbose_name_plural': 'Szkoły',
            },
        ),
    ]
