# Generated by Django 2.0.2 on 2018-07-17 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi być podany ...', regex='^\\d{5,15}$')], verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='school',
            name='authority',
            field=models.CharField(max_length=100, verbose_name='Organ prowadzący'),
        ),
    ]
