# Generated by Django 2.0.2 on 2018-07-17 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0003_auto_20180717_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.RegexValidator(message='Wprowadź prawidłowy numer telefonu', regex='^[\\w.-]+@[\\w.-]+.\\w+$')], verbose_name='Adres email sekretariatu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Imię i nazwisko Dyrektora Szkoły'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='olimpiada.School'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Wprowadź prawidłowy numer telefonu', regex='^\\d{5,15}$')], verbose_name='Numer telefonu sekretariatu / dyrekcji'),
        ),
    ]
