# Generated by Django 2.0.2 on 2018-07-17 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olimpiada', '0005_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('modification_date', models.DateField(auto_now_add=True, verbose_name='Data modyfikacji')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('lead', models.CharField(blank=True, max_length=300, verbose_name='Lead')),
                ('text', models.TextField(verbose_name='Tekst artykułu')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
