# Generated by Django 2.0.2 on 2018-07-18 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0006_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='tagi'),
            preserve_default=False,
        ),
    ]
