# Generated by Django 2.0.2 on 2018-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0007_auto_20180718_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='tagi'),
        ),
    ]
