# Generated by Django 2.0.2 on 2018-07-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0008_auto_20180718_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Umieść na stronie'),
        ),
    ]
