# Generated by Django 2.0.2 on 2018-07-20 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0009_article_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='adres@szkola.pl', max_length=50, validators=[django.core.validators.RegexValidator(message='Wprowadź prawidłowy numer telefonu', regex='^[\\w.-]+@[\\w.-]+.\\w+$')], verbose_name='Adres email sekretariatu'),
        ),
    ]
