# Generated by Django 2.0.2 on 2018-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0011_acceptance_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptance',
            options={'verbose_name': 'Zgoda', 'verbose_name_plural': 'Zgody'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Uczeń', 'verbose_name_plural': 'Uczniowie'},
        ),
        migrations.AddField(
            model_name='acceptance',
            name='title',
            field=models.CharField(default='brak', max_length=100, verbose_name='Tytuł'),
            preserve_default=False,
        ),
    ]
