# Generated by Django 2.0.2 on 2018-07-26 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0012_auto_20180723_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='uczen@szkola.pl', max_length=50, validators=[django.core.validators.RegexValidator(message='Wprowadź prawidłowy numer telefonu', regex='^[\\w.-]+@[\\w.-]+.\\w+$')], verbose_name='Adres email'),
        ),
        migrations.AddField(
            model_name='student',
            name='obj_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='Klucz obiektu'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='obj_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='Klucz obiektu'),
        ),
    ]
